# permissions for end users to view oldpodlists.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: oldpodlist-operator
    app.kubernetes.io/managed-by: kustomize
  name: oldpodlist-viewer-role
rules:
- apiGroups:
  - example.example.com
  resources:
  - oldpodlists
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - example.example.com
  resources:
  - oldpodlists/status
  verbs:
  - get
